### PR TITLE
Fix and improve styles

### PR DESCRIPTION
**Pull request by Lenninlasd**
Fix and improve css styles of the application

screen shot 2017-05-22 at 12 24 42

screen shot 2017-05-22 at 14 30 03

screen shot 2017-05-23 at 15 48 39

### CODE REVIEW

**Comment by capooti** [comment]
thanks

**Comment by Lenninlasd** [comment]
Hi @capooti for the next you can squash and merge the PR in order to have just one commit.

**Comment by capooti** [comment]
OK, good idea. But isn't it the recommended approach to squash commits before submitting the PR?

**Comment by Lenninlasd** [comment]
I mean, Github allows this option through the `Squash and merge` button.

screen shot 2017-05-22 at 12 24 42

**Comment by capooti** [comment]
I didn't know that there is such an handy thing now :)

**Pull request merged**
