### PR TITLE
Merge remotes

### PR DESCRIPTION
**Pull request by JorgeMartinezG**

### CODE REVIEW

**Comment by waybarrios** [comment]
merge piensa fork to piensa branch, it is necessary to be updated!

**Comment by capooti** [comment]
@JorgeMartinezG and @waybarrios  I guess I can look at this and close the other PR? (https://github.com/cga-harvard/worldmap/pull/2)

**Comment by capooti** [comment]
sorry, I see it was already closed. I will look into this one then.

**Comment by JorgeMartinezG** [comment]
@capooti Can we merge master and piensa branches in order for all to work in the same branch?. Because I dont have privileges, I will work on another branch and I'll try to send PRs daily.

**Comment by capooti** [comment]
Yes, let's definitely merge. I will do it right today

**Comment by capooti** [comment]
Do you want to send it as a PR to master?

**Pull request merged**
